name: Publish Release

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup git config
        run: |
          git config user.name "release-bot"
          git config user.email "<>"

      - name: Set up JDK 11
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: maven

      - name: Get version from tag
        id: get_version
        run: |
          releaseVersion="${GITHUB_REF/refs\/tags\//}"
          releaseVersion="${releaseVersion//v/}"
          echo "VERSION=$releaseVersion" >> $GITHUB_OUTPUT

      - name: Update version pom.xml
        run: mvn --no-transfer-progress versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Install gpg key
        run: echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import

      - name: Publish
        run: mvn --no-transfer-progress --batch-mode deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.D11_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.D11_NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Bump version
        run: .ci/scripts/bump-version.sh
